version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.7.0
    - 2.7.2
    - 2.7.4
  - dependency-name: scipy
    versions:
    - 1.6.1
    - 1.6.2
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: ipython
    versions:
    - 7.20.0
    - 7.21.0
  - dependency-name: sphinx-rtd-theme
    versions:
    - 0.5.1
  - dependency-name: numpy
    versions:
    - 1.20.1
  - dependency-name: pydocstyle
    versions:
    - 5.1.1
